### ISSUE TITLE
Integrate Signal-Encryption plugin

### ISSUE THREAD

**Issue by tassadarius** [jcryptool/crypto#376]
#### About

Students at FH-Hagenberg started a project to visualize the [Signal-Ecryption algorithm](https://www.signal.org/docs/).
The code has been lying around some time so finish and integrate it.

#### TODOs

- [x] finalize descriptions
- [x] Create basic online help
- [ ] Create basic context help
- [x] Create English translation
- [x] Clean-up code to minimum acceptable level

#### Bugs

- [x] Recreating only one key leads to error
 >      I suspect it uses the wrong one-time key and is then confused
- [ ] Sometimes when going back and forth a value is missing in the capturer
>      I could narrow it down that if you switch state somewhat randomly 
>      (probably there is a pattern) a value is missing when switching to bob sending
```
java.lang.NullPointerException: Cannot invoke "org.whispersystems.libsignal.ecc.ECPublicKey.serialize()" because "this.sendingCapture.publicDiffieHellmanRatchetKey" is null
	at org.jcryptool.visual.signalencryption.communication.MessageContext.diffieHellmanSenderPublicKey(MessageContext.java:154)
	at org.jcryptool.visual.signalencryption.ui.DoubleRatchetBobSendingLogic.updateSendingKeyDisplayInformation(DoubleRatchetBobSendingLogic.java:490)
	at org.jcryptool.visual.signalencryption.ui.DoubleRatchetBobSendingLogic$BobSendingStep$2.switchState(DoubleRatchetBobSendingLogic.java:63)
	at org.jcryptool.visual.signalencryption.ui.DoubleRatchetStep.next(DoubleRatchetStep.java:21)
	at org.jcryptool.visual.signalencryption.ui.DoubleRatchetAliceSendingLogic.stepForward(DoubleRatchetAliceSendingLogic.java:505)
	at org.jcryptool.visual.signalencryption.ui.DoubleRatchetView.lambda$3(DoubleRatchetView.java:179)
	at org.jcryptool.visual.signalencryption.util.UiUtils$1.widgetSelected(UiUtils.java:100)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5745)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5013)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4507)
```
- [x] Small layout problems (especially with those expanders  😠)

#### Optional improvements

- [ ] Create good online help
- [ ] Create good context help
- [x] Refactor code to improve readability

**Comment by tassadarius** [comment]
I would say we can close this. If there are no Mac/Windows problems it's production ready IMHO

**Comment by simlei** [comment]
What a great plugin 👌
